name: BuildAndTest

on:
  push:
    branches: [ main ]
#   pull_request:
#     branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
        
    - name: Install dependencies
      working-directory: source/
      run: dotnet restore
      
    - name: Build with dotnet
      working-directory: source/
      run: dotnet build --configuration Release
      
    - name: Test
      working-directory: source/
      run: dotnet test --verbosity normal
      
    - name: Publish
      working-directory: ${{ github.workspace}}/source/
      run: dotnet publish HelloWorld.sln --configuration Release --output ${{ github.workspace}}/Build/Zip/publish --runtime win-x86 --self-contained true -p:PublishTrimmed=true -p:PublishSingleFile=true -p:PublishArtifact=true

#     - name: Archive Release
#       uses: thedoctor0/zip-release@master
#       with:
#         type: 'zip'
#         filename: 'makezip.zip'
#         exclusions: '*.git* /*node_modules/* .editorconfig'

    - uses: actions/upload-artifact@v1
      with:
        name: my-artifact-1
        path: 'Build/Zip/'
