name: BuildAndTest

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
        
    - name: Install dependencies
      working-directory: source/
      run: dotnet restore
      
    - name: Build with dotnet
      working-directory: source/
      run: dotnet build --configuration Release
      
    - name: Test
      working-directory: source/
      run: dotnet test --verbosity normal

    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: 'makezip.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'
        
    - uses: actions/upload-artifact@v1
      with:
        name: my-artifact-1
        path: 'makezip.zip'

    - name: Publish
      working-directory: ${{ github.workspace}}/source/
      run: |
        dotnet publish HelloWorld.sln --configuration Release -r win-x64 --self-contained true -o ${{ github.workspace }}/Build/Zip/publish -p:PublishTrimmed=true -p:PublishSingleFile=true -p:PublishArtifact=true 
        echo "welcome"
        echo ${{ github.workspace }}
        echo ${{ github.workspace}}/Build/Zip/publish
        zip -r win-x64 ${{ github.workspace}}/Build/Zip/publish
  
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: 'makezip3.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'
        
    - uses: actions/upload-artifact@v1
      with:
        name: my-artifact-2
        path: 'makezip3.zip'
        
    - uses: actions/upload-artifact@v1
      with:
        name: my-artifact-2
        path: 'Build/Zip/'
