name: BuildAndTest

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
        
    - name: Install dependencies
      working-directory: source/
      run: dotnet restore
      
    - name: Build with dotnet
      working-directory: source/
      run: dotnet build --configuration Release
      
    - name: Test
      working-directory: source/
      run: dotnet test --verbosity normal
      
    - name: Publish
      working-directory: source/
      run: |
        dotnet publish HelloWorld.sln --configuration Release --runtime win-x86 --self-contained true --output ${{ github.workspace}}/Build/Zip/publish -p:PublishTrimmed=true -p:PublishSingleFile=true -p:PublishArtifact=true 
        echo "welcome"
        zip ${{ github.workspace}}/Build/Zip/publish
      
    - uses: actions/upload-artifact@v1
      with:
        name: my-artifact-1
        path: '${{ github.workspace}}/Build/Zip/'
